sudo: false
dist: xenial
language: node_js
node_js: "11.0.0"
stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "Test VSCode Extension"
      install: npm install
      before_script: npm run build
      script: xvfb-run npm test --silent

    - &release
      stage: release
      name: "Publish GitHub Release"
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/
      before_install: npm install -g vsce
      install: npm install --production
      script:  vsce package
      deploy: &github
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: "*.vsix"
        skip_cleanup: true
        on:
          tags: true
    - <<: *release
      name: "Publish GitHub Pre-release"
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+.+$/
      deploy:
        <<: *github
        prerelease: true
