sudo: false
dist: xenial
language: node_js
stages:
  - test
  - release
  - test Release

jobs:
  include:
    - stage: test
      node_js: "11.0.0"
      name: "Test VSCode Extension"
      install: npm install
      before_script: npm run build
      script: xvfb-run npm test --silent

    - &release
      stage: release
      name: "Publish GitHub Release"
      node_js: "11.0.0"
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/
      before_install: npm install -g vsce
      install: npm install --production
      script:  vsce package
      deploy: &github
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: "*.vsix"
        skip_cleanup: true
        on:
          tags: true
    - <<: *release
      name: "Publish GitHub Pre-release"
      node_js: "11.0.0"
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+.+$/
      deploy:
        <<: *github
        prerelease: true
    - &testrelease
      stage: test Release
      os: windows
      name: "Test extension package on Windows"
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+/
      install:
        - npm install
        - npm run build
        - export PKG_VERSION=$(npm run version --silent)
        - wget https://github.com/torrentalle/vscode-perl-moose/releases/download/$TRAVIS_TAG/perl-moose-$PKG_VERSION.vsix
      script:
        - npm run test-package
    - <<: *testrelease
      os: osx
      node_js: "8.11.3"
      name: "Test extension package on OSX"
    - <<: *testrelease
      os: linux
      node_js: "11.0.0"
      name: "Test extension package on Linux"
      script:
        - xvfb-run npm run test-package
